// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAtrio_App_Test.EF;

#nullable disable

namespace WebAtrioAppTest.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAtrio_App_Test.Entities.Emploi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom_Entreprise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poste")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Emplois");
                });

            modelBuilder.Entity("WebAtrio_App_Test.Entities.PersonneEmploi", b =>
                {
                    b.Property<int>("PersonneId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("EmploiId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("Date_Debut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_Fin")
                        .HasColumnType("datetime2");

                    b.HasKey("PersonneId", "EmploiId");

                    b.HasIndex("EmploiId");

                    b.ToTable("PersonneEmplois");
                });

            modelBuilder.Entity("WebAtrio_App_Test.Personne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date_Naiss")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personnees");
                });

            modelBuilder.Entity("WebAtrio_App_Test.Entities.PersonneEmploi", b =>
                {
                    b.HasOne("WebAtrio_App_Test.Entities.Emploi", "Emploi")
                        .WithMany("PersonneEmplois")
                        .HasForeignKey("EmploiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAtrio_App_Test.Personne", "Personne")
                        .WithMany("PersonneEmplois")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emploi");

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("WebAtrio_App_Test.Entities.Emploi", b =>
                {
                    b.Navigation("PersonneEmplois");
                });

            modelBuilder.Entity("WebAtrio_App_Test.Personne", b =>
                {
                    b.Navigation("PersonneEmplois");
                });
#pragma warning restore 612, 618
        }
    }
}
